version: '3'
services:
  web:
    build: .
    ports:
      - "8002:5000"
    deploy:
      resources:
        limits:
          memory: 70M  # Strict Limit
          cpus: '0.5'
    restart: always
    container_name: nhs_portal_ctf

    